//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.29 at 01:19:25 PM IST 
//


package org.o2.registersvc.schema.res;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;




/**
 * <p>Java class for CreditCheckType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CreditCheckType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="rateofper" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="creditstatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CreditCheckType", propOrder = {
    "rateofper",
    "creditstatus"
})
public class CreditCheckType {

    protected float rateofper;
    @XmlElement(required = true)
    protected String creditstatus;

    /**
     * Gets the value of the rateofper property.
     * 
     */
    public float getRateofper() {
        return rateofper;
    }

    /**
     * Sets the value of the rateofper property.
     * 
     */
    public void setRateofper(float value) {
        this.rateofper = value;
    }

    /**
     * Gets the value of the creditstatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreditstatus() {
        return creditstatus;
    }

    /**
     * Sets the value of the creditstatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreditstatus(String value) {
        this.creditstatus = value;
    }

}
